sudo: required
language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker build -t jakeklassen/docker-react -f Dockerfile.dev .

script:
  - docker run --env CI=true jakeklassen/docker-react yarn test --coverage
